// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxOUscPbUtFFbq6tT5KAmFDwT33xlZ360',
    appId: '1:416829496123:web:65f7582bc06c377827751e',
    messagingSenderId: '416829496123',
    projectId: 'school-connect-app-e4c40',
    authDomain: 'school-connect-app-e4c40.firebaseapp.com',
    storageBucket: 'school-connect-app-e4c40.firebasestorage.app',
    measurementId: 'G-SF8NJX32TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlLK9Ibxk_rQ9C6oahfg13BuKvLgBgtU',
    appId: '1:416829496123:android:dcb803135b2f344c27751e',
    messagingSenderId: '416829496123',
    projectId: 'school-connect-app-e4c40',
    storageBucket: 'school-connect-app-e4c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI_CZwHxiPT_Ol4BEQ6rbilg6nX5rtlPU',
    appId: '1:416829496123:ios:cae3cd657ade6d0927751e',
    messagingSenderId: '416829496123',
    projectId: 'school-connect-app-e4c40',
    storageBucket: 'school-connect-app-e4c40.firebasestorage.app',
    iosBundleId: 'com.example.ubaFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI_CZwHxiPT_Ol4BEQ6rbilg6nX5rtlPU',
    appId: '1:416829496123:ios:cae3cd657ade6d0927751e',
    messagingSenderId: '416829496123',
    projectId: 'school-connect-app-e4c40',
    storageBucket: 'school-connect-app-e4c40.firebasestorage.app',
    iosBundleId: 'com.example.ubaFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxOUscPbUtFFbq6tT5KAmFDwT33xlZ360',
    appId: '1:416829496123:web:2fe2957f312b1e5427751e',
    messagingSenderId: '416829496123',
    projectId: 'school-connect-app-e4c40',
    authDomain: 'school-connect-app-e4c40.firebaseapp.com',
    storageBucket: 'school-connect-app-e4c40.firebasestorage.app',
    measurementId: 'G-ZDLLG4B4FP',
  );
}
